services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend_prod:
    build:
      context: ./backend
      target: production
    ports:
      - "${BACKEND_PORT}:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - BACKEND_PORT=${BACKEND_PORT}

  frontend_prod:
    build:
      context: ./frontend
      target: production
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend_prod

volumes:
  postgres_data:
